server:
  port: ${SERVER_PORT}
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

spring:
  cloud:
    config:
      enabled: false

#Actuator properties
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    defaults:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure.include: health,info,prometheus,loggers
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    env:
      enabled: true
  server:
    port: ${ACTUATOR_PORT}


logging:
  level:
    ru.skbbank.bm: info
